repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 'v3.2.0'
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml

- repo: local
  hooks:
  - id: typeright
    name: Fix Types
    language: system
    entry: python
    args: ['-m', 'typeright']
    types: [python]
    exclude: &exclude "tests/fixtures/.*"

- repo: https://github.com/timothycrosley/isort
  rev: '5.12.0'
  hooks:
  - id: isort
    args: [--filter-files]
    exclude: *exclude

- repo: https://github.com/pre-commit/mirrors-autopep8
  rev: 'v1.5.4'
  hooks:
  - id: autopep8

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 'v0.790'
  hooks:
  - id: mypy
    entry: dmypy
    args: ['run']
    pass_filenames: false
    exclude: *exclude
